db:
  image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=rootpassword
    - MYSQL_DATABASE=spring
    - MYSQL_USER=username
    - MYSQL_PASSWORD=password
  ports:
    - "3306:3306"
  volumes:
#   - ./db:/docker-entrypoint-initdb.d
    - ./mysql:/var/lib/mysql
web:
  build: ./tomcatDocker
  # Environment variables do not appear to be getting loaded the first time Tomcat starts!
  environment:
    - "JAVA_OPTS=-Denv=prod"
  ports:
    - "80:8080"
  volumes:
    - ./productImg:/var/lib/eproduct/productImage
    - ./productIndex:/var/lib/eproduct/productIndex
    - ./tomcat/webapps:/usr/local/tomcat/webapps
  links:
    - db